language: cpp

os:
  - linux
  - osx

compiler:
  - g++
  - clang++

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"]]; then 
        if ["$CXX" = "g++"]; then export CXX="g++" CC="gcc"; fi
    fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi

script:
  - make
